### ISSUE TITLE
Tumor types

### ISSUE THREAD

**Issue by ShijianRuan** [MrGiovanni/Pixel2Cancer#1]
Thanks for your excell work. In the paper, it was observed that liver, kidney, and pancreas were used for validation. what about other types of tumors? Can you clarify which organ‘s synthetic tumors are suitable for Pixel2Cancer?

**Comment by Arbiter00** [comment]
Our design in this paper focuses on solid organs, such as the liver, pancreas, and kidney. We are now working on synthesizing tumors in organs with cavities, such as the colon, stomach, and esophagus.

**Comment by Yuxiang-Lai117** [comment]
Thank you for your question. Our design in this paper focuses on solid organs such as the liver, pancreas, and kidney. Currently, we are working on synthesizing tumors in organs that have cavities, such as the colon, stomach, and esophagus.
